### ISSUE TITLE
Improve submission status viewing

### ISSUE THREAD

**Issue by vishwakftw** [vbsinha/autojudge#70]
The current way of presenting submission status is not very clean and comfortable for the user.

We should fix this using modals.

**Comment by vishwakftw** [comment]
Closed by #69.

**Comment by prateekkumarweb** [comment]
> Closed by #69.

You could have also added "close #70" in the commit message of the PR while merging and it would have closed this automatically

**Comment by vishwakftw** [comment]
I am aware of GitHub magic words, I just forgot about it😛
