### ISSUE TITLE
Better error localization and informative error messages

### ISSUE THREAD

**Issue by vishwakftw** [vbsinha/autojudge#77]
In the existing version of the app, we don't care about the exact field or set of fields that are causing the error.

For instance, in the case of a duplicate contest name passed at the time of contest creation, we simply get "Contest could not be created", without any other details as to why. Please look at the screenshot below:
![image](https://user-images.githubusercontent.com/23639302/60755911-3164f200-a014-11e9-8523-9b0b0b72705c.png)

A partial fix is to the pass the error string to the front-end, but for people with no domain knowledge, this is not good. Please look below:
![image](https://user-images.githubusercontent.com/23639302/60755918-4f325700-a014-11e9-9b10-412ad20121d2.png)

I propose that we invoke field errors (presented in #76 for date checking). Please look below.
![image](https://user-images.githubusercontent.com/23639302/60755936-856fd680-a014-11e9-920d-4c8a14f8d3a7.png)

If this proposal is cool, I'll point out places where the code will have to be changed.

cc: @prateekkumarweb @vbsinha

**Comment by prateekkumarweb** [comment]
Cool! Go ahead.
