### ISSUE TITLE
Design Training Manual

### ISSUE THREAD

**Issue by vishwakftw** [vbsinha/autojudge#79]
We need to design a training manual for people interested in using this software.

I’m adding a list of points to be covered (should be expanded):

- [x] Create Contest
- [x] Add posters for the contest
- [x] Add participants for the contest
- [x] Update dates
- [x] Add Problem for the contest
- [x] Edit Problem
- [x] Delete Problem
- [x] Delete contest
- [x] Add test cases
- [x] Delete test cases (is this there)
- [x] Make submission
- [x] View all submissions and the statuses
- [x] Add comment
- [x] Update poster score
- [x] Download submissions
- [x] Download CSV of submission scores

**Comment by vbsinha** [comment]
We do not support deleting comments and so I am removing that from TODO.

**Comment by vishwakftw** [comment]
Anything else you can think of? I see everything's done.
